version: '3.8'

services:
  # PostgreSQL Database only
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: instashorts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  # Using standard port
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d instashorts"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: